### ISSUE TITLE
Request Rating & Review

### ISSUE THREAD

**Issue by ericbhanson** [BoomerangProject/boomerang#8]
As a Business, I want to be able to request a rating and review from a Customer so that I can better evaluate my performance and that of my employees.

**Comment by ericbhanson** [comment]
Link to feature: https://skedaddle.productboard.com/feature-board/planning/features/1421681

**Comment by Kyrrui** [comment]
Working on this now. This will actually be two minorly different features - requesting a business review and requesting a worker review. We will also need designs for a business dashboard

**Comment by ericbhanson** [comment]
@Kyrrui do you want two separate issues?

**Comment by Kyrrui** [comment]
Yeah, let's do that, because I've also added a verification step so that a business cannot claim a worker until the worker accepts.

**Comment by Kyrrui** [comment]
I will close this out, as it is working as intended.

**Comment by ericbhanson** [comment]
Added https://github.com/BoomerangProject/boomerang/issues/13 to cover the request for Worker use case.
